# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5a0f5b6b6a9dadf67f7af8e5ddea266213f6baa6aa2f96a3ae91a3fd431d6f7149390180a351912e5e2212d9f64a55f6e8b2779073949328b95076cc3cd8c5ea

test:
  secret_key_base: 013efcc7fd2eb3aa8c010bb8fa1b99c82fdd7489437c1d47a329e96f5d701ac97aea9c1dac7954daf05db6a97d9a21696551ba7c637393c7afa3ff154b192771

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
